#!/usr/bin/env -S PYTHONPATH=../../../../tools/extract-utils python3
#
# SPDX-FileCopyrightText: 2026 The LineageOS Project
# SPDX-License-Identifier: Apache-2.0

"""Extract Xiaomi 13T Android 16 proprietary files into the fresh staging tree.

This module deliberately has no inherited/common module and no blob fixups.
Fixups may only be added after an Android 16 ELF/linker failure demonstrates
that they are necessary.
"""

from os import path

from extract_utils.fixups_lib import lib_fixups as lib_fixups_base
from extract_utils.main import ExtractUtils, ExtractUtilsModule
from extract_utils.tools import android_root


def lib_fixup_vendor_suffix(lib: str, partition: str, *args, **kwargs):
    """Keep partition-specific copies of libraries with the same SONAME distinct."""
    return f"{lib}-vendor" if partition in ("vendor", "odm") else None


def lib_fixup_xiaomi_suffix(lib: str, partition: str, *args, **kwargs):
    """Disambiguate a Xiaomi C++ blob from an unrelated AOSP Rust crate."""
    return f"{lib}-xiaomi" if partition == "system_ext" else None


def lib_fixup_stock_system_suffix(lib: str, partition: str, *args, **kwargs):
    """Keep the stock A16 audio parser on its mutually paired AIDL libraries."""
    return f"{lib}-stock" if partition in ("system", "system_ext") else None


lib_fixups = {
    **lib_fixups_base,
    ("libsink",): lib_fixup_xiaomi_suffix,
    (
        "android.hardware.audio.core-V3-ndk",
        "av-audio-types-aidl-ndk",
    ): lib_fixup_stock_system_suffix,
    (
        "libalsautils",
        "libalsautilsv2",
        "libmisight",
        "android.frameworks.sensorservice@1.0",
        "android.hardware.audio.common@5.0",
        "android.hardware.biometrics.common.thread",
        "android.hardware.bluetooth.audio@2.0",
        "android.hardware.bluetooth.audio@2.1",
        "android.hardware.boot@1.0",
        "android.hardware.boot@1.1",
        "android.hardware.camera.common@1.0",
        "android.hardware.camera.device@1.0",
        "android.hardware.camera.device@3.2",
        "android.hardware.camera.device@3.3",
        "android.hardware.camera.device@3.4",
        "android.hardware.camera.provider@2.4",
        "android.hardware.camera.provider@2.5",
        "android.hardware.camera.provider@2.6",
        "android.hardware.graphics.allocator@2.0",
        "android.hardware.graphics.allocator@3.0",
        "android.hardware.graphics.allocator@4.0",
        "android.hardware.graphics.bufferqueue@1.0",
        "android.hardware.graphics.bufferqueue@2.0",
        "android.hardware.graphics.common@1.0",
        "android.hardware.graphics.common@1.1",
        "android.hardware.graphics.common@1.2",
        "android.hardware.graphics.mapper@2.0",
        "android.hardware.graphics.mapper@2.1",
        "android.hardware.graphics.mapper@3.0",
        "android.hardware.graphics.mapper@4.0",
        "android.hardware.health@1.0",
        "android.hardware.keymaster@3.0",
        "android.hardware.keymaster@4.0",
        "android.hardware.security.keymint-V3-ndk",
        "android.hardware.security.keymint-V4-ndk",
        "android.frameworks.sensorservice-V1-ndk",
        "android.frameworks.stats-V1-ndk",
        "android.frameworks.stats-V2-ndk",
        "android.hardware.audio.common-V3-ndk",
        "android.hardware.audio.common-V4-ndk",
        "android.hardware.audio.core-V2-ndk",
        "android.hardware.audio.core.sounddose-V2-ndk",
        "android.hardware.audio.core.sounddose-V3-ndk",
        "android.hardware.audio.effect-V2-ndk",
        "android.hardware.audio.effect-V3-ndk",
        "android.hardware.biometrics.common-V4-ndk",
        "android.hardware.biometrics.fingerprint-V4-ndk",
        "android.hardware.bluetooth-V1-ndk",
        "android.hardware.bluetooth.audio-V4-ndk",
        "android.hardware.bluetooth.audio-V5-ndk",
        "android.hardware.bluetooth.finder-V1-ndk",
        "android.hardware.bluetooth.ranging-V1-ndk",
        "android.hardware.boot-V1-ndk",
        "android.hardware.camera.common-V1-ndk",
        "android.hardware.camera.common-V2-ndk",
        "android.hardware.camera.device-V3-ndk",
        "android.hardware.camera.metadata-V3-ndk",
        "android.hardware.camera.provider-V3-ndk",
        "android.hardware.common-V2-ndk",
        "android.hardware.common.fmq-V1-ndk",
        "android.hardware.contexthub-V4-ndk",
        "android.hardware.drm-V1-ndk",
        "android.hardware.drm.common-V1-ndk",
        "android.hardware.dumpstate-V1-ndk",
        "android.hardware.gatekeeper-V1-ndk",
        "android.hardware.gnss-V5-ndk",
        "android.hardware.graphics.allocator-V2-ndk",
        "android.hardware.graphics.common-V5-ndk",
        "android.hardware.graphics.common-V6-ndk",
        "android.hardware.graphics.composer3-V2-ndk",
        "android.hardware.graphics.composer3-V3-ndk",
        "android.hardware.graphics.composer3-V4-ndk",
        "android.hardware.health-V1-ndk",
        "android.hardware.health-V4-ndk",
        "android.hardware.ir-V1-ndk",
        "android.hardware.keymaster-V4-ndk",
        "android.hardware.light-V1-ndk",
        "android.hardware.light-V2-ndk",
        "android.hardware.media.bufferpool2-V2-ndk",
        "android.hardware.media.c2-V1-ndk",
        "android.hardware.memtrack-V1-ndk",
        "android.hardware.nfc-V1-ndk",
        "android.hardware.power-V4-ndk",
        "android.hardware.power-V6-ndk",
        "android.hardware.radio-V4-ndk",
        "android.hardware.radio.config-V4-ndk",
        "android.hardware.radio.data-V4-ndk",
        "android.hardware.radio.ims-V3-ndk",
        "android.hardware.radio.messaging-V4-ndk",
        "android.hardware.radio.modem-V4-ndk",
        "android.hardware.radio.network-V4-ndk",
        "android.hardware.radio.sap-V1-ndk",
        "android.hardware.radio.sim-V4-ndk",
        "android.hardware.radio.voice-V4-ndk",
        "android.hardware.secure_element-V1-ndk",
        "android.hardware.security.keymint-V1-ndk",
        "android.hardware.security.rkp-V3-ndk",
        "android.hardware.security.secureclock-V1-ndk",
        "android.hardware.security.sharedsecret-V1-ndk",
        "android.hardware.sensors-V2-ndk",
        "android.hardware.sensors-V3-ndk",
        "android.hardware.soundtrigger3-V1-ndk",
        "android.hardware.soundtrigger3-V3-ndk",
        "android.hardware.tetheroffload-V1-ndk",
        "android.hardware.usb-V3-ndk",
        "android.hardware.usb.gadget-V1-ndk",
        "android.hardware.vibrator-V1-ndk",
        "android.hardware.wifi-V3-ndk",
        "android.hardware.wifi.common-V2-ndk",
        "android.hardware.wifi.hostapd-V3-ndk",
        "android.hardware.wifi.supplicant-V4-ndk",
        "android.media.audio.common.types-V2-ndk",
        "android.media.audio.common.types-V3-ndk",
        "android.media.audio.common.types-V4-ndk",
        "android.media.audio.eraser.types-V1-ndk",
        "android.media.soundtrigger.types-V1-ndk",
        "android.media.soundtrigger.types-V3-ndk",
        "android.system.keystore2-V1-ndk",
        "android.system.suspend-V1-ndk",
        "vendor.mediatek.hardware.audio-V1-ndk",
        "vendor.nxp.nxpnfc_aidl-V1-ndk",
        "vendor.xiaomi.hardware.displayfeature_aidl-V2-ndk",
        "android.hardware.light@2.0",
        "android.hardware.media.bufferpool@2.0",
        "android.hardware.media.c2@1.0",
        "android.hardware.media.c2@1.1",
        "android.hardware.media.c2@1.2",
        "android.hardware.media.omx@1.0",
        "android.hardware.media@1.0",
        "android.hardware.nfc@1.0",
        "android.hardware.nfc@1.1",
        "android.hardware.nfc@1.2",
        "android.hardware.power@1.0",
        "android.hardware.power@1.1",
        "android.hardware.power@1.2",
        "android.hardware.secure_element@1.0",
        "android.hardware.secure_element@1.1",
        "android.hardware.secure_element@1.2",
        "android.hardware.sensors@1.0",
        "android.hardware.sensors@2.0",
        "android.hardware.sensors@2.0-ScopedWakelock",
        "android.hardware.sensors@2.1",
        "android.hardware.soundtrigger3-impl",
        "android.hidl.allocator@1.0",
        "android.hidl.memory.token@1.0",
        "android.hidl.memory@1.0",
        "android.hidl.safe_union@1.0",
        "android.hidl.token@1.0",
        "android.hidl.token@1.0-utils",
        "android.system.suspend@1.0",
        "libOpenCL",
        "lib_android_keymaster_keymint_utils",
        "libaconfig_storage_read_api_cc",
        "libarmnn",
        "libaudio_aidl_conversion_common_ndk",
        "libaudioaidlcommon",
        "libaudioutils",
        "libavservices_minijail",
        "libbase",
        "libbinder",
        "libbt-vendor",
        "libcamera_metadata",
        "libcap",
        "libcodec2",
        "libcodec2_aidl",
        "libcodec2_hal_common",
        "libcodec2_hidl@1.0",
        "libcodec2_hidl@1.1",
        "libcodec2_hidl@1.2",
        "libcodec2_hidl_plugin",
        "libcodec2_soft_common",
        "libcodec2_vndk",
        "libcppbor",
        "libcppbor_external",
        "libcppcose_rkp",
        "libcrypto",
        "libcurl",
        "libcutils",
        "libdmabufheap",
        "libdrm",
        "libdumpstateutil",
        "libexpat",
        "libflatbuffers-cpp",
        "libfmq",
        "libgatekeeper",
        "libgralloctypes",
        "libgrallocusage",
        "libhardware",
        "libhardware_legacy",
        "libhidlbase",
        "libhidlmemory",
        "libhidltransport",
        "libhwbinder",
        "libion",
        "libjpeg",
        "libjsoncpp",
        "libkeymaster4support",
        "libkeymaster_messages",
        "libkeymaster_portable",
        "libkeymint",
        "libkeymint_remote_prov_support",
        "libkeymint_support",
        "libkeystore-engine-wifi-hidl",
        "liblzma",
        "libmedia_helper",
        "libmediautils_vendor",
        "libmeminfo",
        "libmemunreachable",
        "libminijail",
        "libnbaio_mono",
        "libnetutils",
        "libnl",
        "libpcap",
        "libpng",
        "libpower",
        "libprocessgroup",
        "libprocinfo",
        "libpuresoftkeymasterdevice",
        "librilutils",
        "libsensorndkbridge",
        "libsfplugin_ccodec_utils",
        "libsoft_attestation_cert",
        "libspeexresampler",
        "libsqlite",
        "libssl",
        "libstagefright_aidl_bufferpool2",
        "libstagefright_bufferpool@2.0.1",
        "libstagefright_bufferqueue_helper",
        "libstagefright_foundation",
        "libsysutils",
        "libtextclassifier_hash",
        "libtflite",
        "libtinyalsa",
        "libtinyalsav2",
        "libtinycompress",
        "libtinyxml2",
        "libtrusty",
        "libui",
        "libunwindstack",
        "libutils",
        "libutilscallstack",
        "libwifi-hal",
        "libwifi-system-iface",
        "libxml2",
        "libz",
        "server_configurable_flags",
        "vendor.mediatek.hardware.audio-impl",
        "vendor.mediatek.hardware.mtkpower@1.1",
        "vendor.mediatek.hardware.mtkpower@1.2",
        "vendor.nxp.nxpese@1.0",
        "vendor.xiaomi.hardware.displayfeature@1.0",
        "vendor.mediatek.hardware.aee-V1-ndk",
        "vendor.mediatek.hardware.aee@1.0",
        "vendor.mediatek.hardware.aee@1.1",
        "vendor.mediatek.hardware.dmc-V1-ndk",
        "vendor.mediatek.hardware.lbs@1.0",
        "vendor.mediatek.hardware.log-V1-ndk",
        "vendor.mediatek.hardware.mtkpower@1.0",
        "vendor.mediatek.hardware.videotelephony-V1-ndk",
        "vendor.xiaomi.hardware.misys.common-V3-ndk",
        "vendor.xiaomi.hardware.misys.core-V1-ndk",
        "xiaomi.system.hypsys.common-V1-ndk",
    ): lib_fixup_vendor_suffix,
}


module = ExtractUtilsModule(
    "aristotle",
    "xiaomi",
    # extract-utils is rooted at derp/, while this independent implementation
    # must remain one directory above it until validation is complete.
    device_rel_path="../fresh/device/xiaomi/aristotle",
    blob_fixups={},
    lib_fixups=lib_fixups,
    namespace_imports=[
        "hardware/mediatek",
        "hardware/xiaomi",
    ],
)

# Keep all generated output isolated from the historical/active vendor tree.
# Generate final-tree path references while physically staging output under
# fresh/. This makes the generated vendor tree relocatable without rewriting.
project_root = path.realpath(path.join(android_root, ".."))
module.vendor_rel_path = "vendor/xiaomi/aristotle"
module.vendor_path = path.join(project_root, "fresh/vendor/xiaomi/aristotle")
module.vendor_rro_path = path.join(module.vendor_path, "rro_overlays")


if __name__ == "__main__":
    ExtractUtils.device(module).run()
